ccmendpoint: ccm_lb 
postgres: postgres_host
logcollector: log_host
ccmlist:
- name: ccm1
  host: 1.1.1.1
- name: ccm2
  host: 2.2.2.2
regionlist:
- name: aws-sa-east-1
  ccoendpoint: cco_lb
  ccolist:
  - name: cco-aws1
    host: 3.3.3.3
  - name: cco-aws2
    host: 4.4.4.4
  - name: cco-aws3
    host: 5.5.5.5
  rabbitendpointpublic: rabbit_pub_lb
  rabbitendpointprivate: rabbit_priv_lb 
  rabbitlist:
  - name: rabbit-aws1
    host: 6.6.6.6
  - name: rabbit-aws2
    host: 7.7.7.7
- name: azure-sp
  ccoendpoint: cco_lb
  ccolist:
  - name: cco-azure1
    host: 3.3.3.3
  - name: cco-azure2
    host: 4.4.4.4
  - name: cco-azure3
    host: 5.5.5.5
  rabbitendpointpublic: rabbit_pub_lb
  rabbitendpointprivate: rabbit_priv_lb 
  rabbitlist:
  - name: rabbit-azure1
    host: 6.6.6.6
  - name: rabbit-azure2
    host: 7.7.7.7

